# Generated by Django 3.1.4 on 2021-01-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='название')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='актив')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='изменен')),
            ],
        ),
    ]
